spring.application.name=food

server.port=8080
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/FOOD
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.jpa.show-sql=true
jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000




## ----------------------
## Logging
## ----------------------
## Log file location and name
#logging.file.path=C:\Users\dawoo\jdb\lessons\food
#logging.file.name=C:\Users\dawoo\jdb\lessons\food\foods\food.log
#
## Logback rolling policy
#logging.logback.rollingpolicy.max-history=7
#logging.logback.rollingpolicy.max-file-size=100MB
#logging.logback.rollingpolicy.total-size-cap=500MB